version: '3.8'

services:
  app:
    build: .
    container_name: mocau-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_CONN=${DB_CONN}
      - SECRET=${SECRET}
      - SWAGGER_HOST=${SWAGGER_HOST}
      - GIN_MODE=release
      - PORT=3000
    volumes:
      - ./static:/root/static
