version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mocau-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: base_project
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: mocau-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_CONN=app_user:app_password@tcp(mysql:3306)/base_project?charset=utf8mb4&parseTime=True&loc=Local
      - SECRET=vktruzg
      - GIN_MODE=release
      - PORT=3000
    depends_on:
      - mysql
    volumes:
      - ./static:/root/static

  redis:
    image: redis:7-alpine
    container_name: mocau-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
