# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" > .env
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull base images
        run: |
          docker pull golang:1.23-alpine || echo "Failed to pull golang:1.23-alpine"
          docker pull alpine:latest || echo "Failed to pull alpine:latest"
      - name: Build docker image
        run: |
          for i in {1..3}; do
            timeout 600 docker build --network=default --build-arg HTTP_PROXY= --build-arg HTTPS_PROXY= -t vktrung/go . && break
            echo "Attempt $i failed, retrying..."
            sleep 15
          done
      - name: Push image to docker hub
        run: docker push vktrung/go:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull vktrung/go:latest
      - name: Delete old container
        run: docker rm -f go-container
      - name: Run docker container
        run: docker run -d -p 4040:4040 --name go-container vktrung/go
